# Data bilan tanishuv

In [115]:
import pandas as pd 
df=pd.read_csv('student_performance.csv')

In [116]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            500 non-null    str
 1   gender                500 non-null    str
 2   age                   500 non-null    int64
 3   study_hours_per_week  500 non-null    int64
 4   attendance_rate       500 non-null    float64
 5   parent_education      383 non-null    str
 6   internet_access       500 non-null    str
 7   extracurricular       500 non-null    str
 8   previous_score        500 non-null    int64
 9   final_score           500 non-null    int64
 10  passed                500 non-null    str
dtypes: float64(1), int64(4), str(6)
memory usage: 43.1 KB

In [117]:
df.isnull().sum()

student_id                0
gender                    0
age                       0
study_hours_per_week      0
attendance_rate           0
parent_education        117
internet_access           0
extracurricular           0
previous_score            0
final_score               0
passed                    0
dtype: int64

In [118]:
df['parent_education'] = df['parent_education'].fillna('Unknown')

In [119]:
df.isnull().sum()

student_id              0
gender                  0
age                     0
study_hours_per_week    0
attendance_rate         0
parent_education        0
internet_access         0
extracurricular         0
previous_score          0
final_score             0
passed                  0
dtype: int64

In [120]:
df.sample(10)

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
376,STU0377,Female,19,2,85.2,Master,Yes,Yes,93,49,No
71,STU0072,Female,17,4,75.3,Master,Yes,No,92,34,No
452,STU0453,Male,15,22,96.7,Unknown,No,No,51,59,Yes
124,STU0125,Male,18,2,81.0,Unknown,No,Yes,38,39,No
479,STU0480,Female,18,9,95.2,Unknown,Yes,Yes,71,53,Yes
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
336,STU0337,Male,16,26,56.2,PhD,No,No,70,79,Yes
345,STU0346,Male,15,2,85.4,High School,Yes,No,74,44,No
146,STU0147,Male,15,25,76.5,PhD,No,No,73,65,Yes
185,STU0186,Female,16,28,89.0,PhD,No,Yes,47,65,Yes

# Encoding

In [121]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [122]:
df=encodla(df)

In [123]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    500 non-null    int64
 1   age                           500 non-null    int64
 2   study_hours_per_week          500 non-null    int64
 3   attendance_rate               500 non-null    float64
 4   previous_score                500 non-null    int64
 5   final_score                   500 non-null    int64
 6   gender_Female                 500 non-null    int64
 7   gender_Male                   500 non-null    int64
 8   parent_education_Bachelor     500 non-null    int64
 9   parent_education_High School  500 non-null    int64
 10  parent_education_Master       500 non-null    int64
 11  parent_education_PhD          500 non-null    int64
 12  parent_education_Unknown      500 non-null    int64
 13  internet_access_No            500 non-null    int64
 14  internet_access_Yes           500 non-null    int64
 15  extracurricular_No            500 non-null    int64
 16  extracurricular_Yes           500 non-null    int64
 17  passed_No                     500 non-null    int64
 18  passed_Yes                    500 non-null    int64
dtypes: float64(1), int64(18)
memory usage: 74.3 KB

# Scaling

In [124]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [125]:
def scaling_qil(df):
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [126]:
df=scaling_qil(df)

In [127]:
df.sample(15)

,student_id,age,study_hours_per_week,attendance_rate,previous_score,final_score,gender_Female,gender_Male,parent_education_Bachelor,parent_education_High School,parent_education_Master,parent_education_PhD,parent_education_Unknown,internet_access_No,internet_access_Yes,extracurricular_No,extracurricular_Yes,passed_No,passed_Yes
158,0.316633,0.75,0.857143,0.562249,0.615385,0.600000,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
422,0.845691,0.50,0.821429,0.712851,0.984615,0.746667,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
0,0.000000,0.00,0.821429,0.273092,0.169231,0.626667,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
353,0.707415,0.50,0.071429,0.552209,0.569231,0.333333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
452,0.905812,0.00,0.714286,0.933735,0.323077,0.520000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
129,0.258517,0.00,0.428571,0.273092,0.415385,0.480000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
156,0.312625,0.25,0.357143,0.779116,0.676923,0.466667,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
293,0.587174,0.75,0.357143,0.427711,0.630769,0.493333,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
63,0.126253,0.75,0.642857,0.562249,0.261538,0.546667,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
323,0.647295,0.25,0.785714,0.865462,0.476923,0.866667,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
258,0.517034,0.75,0.321429,0.273092,0.969231,0.266667,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
355,0.711423,0.75,0.000000,0.228916,0.000000,0.213333,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
433,0.867735,0.25,0.071429,0.823293,0.661538,0.333333,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
438,0.877756,0.25,0.785714,0.684739,0.184615,0.733333,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
469,0.939880,0.50,0.750000,0.246988,0.061538,0.480000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

# Train

In [128]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    500 non-null    float64
 1   age                           500 non-null    float64
 2   study_hours_per_week          500 non-null    float64
 3   attendance_rate               500 non-null    float64
 4   previous_score                500 non-null    float64
 5   final_score                   500 non-null    float64
 6   gender_Female                 500 non-null    float64
 7   gender_Male                   500 non-null    float64
 8   parent_education_Bachelor     500 non-null    float64
 9   parent_education_High School  500 non-null    float64
 10  parent_education_Master       500 non-null    float64
 11  parent_education_PhD          500 non-null    float64
 12  parent_education_Unknown      500 non-null    float64
 13  internet_access_No            500 non-null    float64
 14  internet_access_Yes           500 non-null    float64
 15  extracurricular_No            500 non-null    float64
 16  extracurricular_Yes           500 non-null    float64
 17  passed_No                     500 non-null    float64
 18  passed_Yes                    500 non-null    float64
dtypes: float64(19)
memory usage: 74.3 KB

In [129]:
X = df.drop([
    'student_id',
    'final_score',
    'passed_No',
    'passed_Yes'
], axis=1)

y = df['passed_Yes']

In [130]:
y

0      1.0
1      0.0
2      0.0
3      1.0
4      1.0
      ...
495    0.0
496    1.0
497    1.0
498    1.0
499    1.0
Name: passed_Yes, Length: 500, dtype: float64

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Evaluation

In [133]:
from sklearn.linear_model import LogisticRegression

In [134]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [135]:
y_pred=model.predict(X_test)
y_pred

array([1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1.])

In [136]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

Accuracy: 0.86
Precision: 0.8289473684210527
Recall: 0.984375
F1: 0.9

# Decision tree

In [137]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [138]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

Accuracy: 0.75
Precision: 0.7746478873239436
Recall: 0.859375
F1: 0.8148148148148148

# Random Forest

In [139]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [140]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

Accuracy: 0.83
Precision: 0.8051948051948052
Recall: 0.96875
F1: 0.8794326241134752

In [141]:
from tabulate import tabulate

result = [
    ['Logistic Regression',0.86,0.82,0.98,0.9],
    ['Decision Tree',0.73,0.76,0.84,0.8],
    ['Random Forest',0.84,0.82,0.95,0.88],
]

headers = ['Algorithm', 'Accuracy', 'Precision', 'Recall', 'F1']

table = tabulate(result, headers=headers, tablefmt='grid')

print(table)

+---------------------+------------+-------------+----------+------+
| Algorithm           |   Accuracy |   Precision |   Recall |   F1 |
+=====================+============+=============+==========+======+
| Logistic Regression |       0.86 |        0.82 |     0.98 | 0.9  |
+---------------------+------------+-------------+----------+------+
| Decision Tree       |       0.73 |        0.76 |     0.84 | 0.8  |
+---------------------+------------+-------------+----------+------+
| Random Forest       |       0.84 |        0.82 |     0.95 | 0.88 |
+---------------------+------------+-------------+----------+------+